# GitHub repository settings
# Used with Settings GitHub App: https://github.com/apps/settings

repository:
  name: muno
  description: 🐙 MUNO - Multi-repository UNified Orchestration. Manage multiple git repositories with monorepo-like convenience.
  homepage: https://github.com/taokim/muno
  topics:
    - muno
    - multi-repo
    - monorepo
    - git
    - orchestration
    - developer-tools
    - cli
    - golang
    - repository-management
    - devops
    - musinsa
    - workspace-management
    - tree-navigation
    - lazy-loading
    - octopus
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: security
    color: ee0701
    description: Security-related issues
  - name: performance
    color: 5319e7
    description: Performance improvements
  - name: testing
    color: bfd4f2
    description: Testing-related changes
  - name: ci/cd
    color: fbca04
    description: Continuous Integration/Deployment
  - name: multi-repo
    color: 1d76db
    description: Related to multi-repository features
  - name: octopus
    color: 98d8c8
    description: Related to MUNO octopus features

# Milestones
milestones:
  - title: v1.0.0 - Stable Release
    description: First stable release of MUNO
    state: open
  - title: v0.7.0 - Feature Complete Beta
    description: All planned features implemented
    state: open

# Branch protection rules would go here, but require admin access