# Example scope-based configuration for repo-claude
# This shows the new scope-based approach (Phase 1 complete)

workspace:
  name: "e-commerce-platform"
  manifest:
    remote_name: "origin"
    remote_fetch: "https://github.com/mycompany/"
    default_revision: "main"
    projects:
      # Backend services
      - name: "auth-service"
        groups: "backend,services"
      - name: "order-service"
        groups: "backend,services,order"
      - name: "payment-service"
        groups: "backend,services,order"
      - name: "inventory-service"
        groups: "backend,services"
      - name: "shipping-service"
        groups: "backend,services,order"
      
      # Frontend applications
      - name: "web-app"
        groups: "frontend,ui"
      - name: "mobile-app"
        groups: "mobile,ui"
      - name: "admin-dashboard"
        groups: "frontend,ui,admin"
      
      # Shared infrastructure
      - name: "shared-libs"
        groups: "shared,core"
      - name: "api-gateway"
        groups: "backend,gateway"

# Scopes define working contexts that group related repositories
scopes:
  # Backend development scope
  backend:
    repos: ["*-service", "api-gateway"]  # Wildcards match all services
    description: "All backend services and API gateway"
    model: "claude-sonnet-4"
    auto_start: true
  
  # Frontend development scope
  frontend:
    repos: ["web-app", "mobile-app", "admin-dashboard"]
    description: "Frontend and mobile development"
    model: "claude-sonnet-4"
    auto_start: true
    dependencies: ["backend"]  # Frontend often needs backend running
  
  # Full-stack development scope
  fullstack:
    repos: ["backend/*", "web-app", "shared-libs"]  # Pattern matching supported
    description: "Full-stack development with web focus"
    model: "claude-sonnet-4"
    auto_start: false
  
  # Task-specific scopes
  order-flow:
    repos: ["order-service", "payment-service", "inventory-service", "shipping-service"]
    description: "Order processing pipeline development"
    model: "claude-sonnet-4"
    auto_start: false
  
  auth-system:
    repos: ["auth-service", "api-gateway", "shared-libs"]
    description: "Authentication and authorization system"
    model: "claude-sonnet-4"
    auto_start: false
  
  mobile:
    repos: ["mobile-app", "api-gateway"]
    description: "Mobile app with API gateway"
    model: "claude-sonnet-4"
    auto_start: false
  
  # Minimal scope for quick fixes
  minimal:
    repos: ["shared-libs"]
    description: "Minimal scope for shared library work"
    model: "claude-sonnet-4"
    auto_start: false

# Usage examples:
# rc start                    # Start all auto-start scopes (backend, frontend)
# rc start backend            # Start backend scope in new tab
# rc start order-service      # Start scope containing order-service
# rc start --new-window       # Force new window instead of tab
# rc ps                       # List running scopes with numbers
# rc kill 1                   # Kill scope #1 from ps output
# rc kill backend             # Kill backend scope by name