# GitHub Pages Configuration for MUNO
title: MUNO
description: 🐙 Multi-repository UNified Orchestration - Manage multiple git repositories with monorepo-like convenience
baseurl: "/muno"
url: "https://taokim.github.io"
logo: ../assets/muno-logo.png
show_downloads: true
google_analytics: 

# SEO Related
lang: en_US
author:
  name: Tao Kim
  email: 
  twitter: 

# Social Media
twitter:
  card: summary_large_image
  title: MUNO - Multi-repository Orchestration
  description: Manage multiple git repositories with monorepo-like convenience
  image: ../assets/muno-social-preview.png

# Open Graph
og:
  title: MUNO
  type: website
  url: https://github.com/taokim/muno
  image: ../assets/muno-social-preview.png
  description: 🐙 Multi-repository UNified Orchestration
  site_name: MUNO

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap