name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  # Add this to allow writing to other repos
  actions: write
  
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we're on the tag ref, not detached HEAD
          ref: ${{ github.ref }}
          
      - name: Fetch tags
        run: |
          git fetch --force --tags
          echo "Current ref: ${{ github.ref }}"
          echo "Current tag: ${{ github.ref_name }}"
          git describe --tags --exact-match || echo "Not on a tag"
          git log -1 --oneline

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}